services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: l34ft1t1SZ3K3Y
      MYSQL_DATABASE: leafItDB
      MYSQL_USER: leafItUser
      MYSQL_PASSWORD: l34ft1t1SZ3K3YUS3R
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: leafItUser
      PMA_PASSWORD: l34ft1t1SZ3K3YUS3R
    ports:
      - "8080:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
